### ISSUE TITLE
read device configuration on init

### ISSUE THREAD

**Issue by bodokaiser** [bodokaiser/houston#4]
It would be preferable to read the dds state from the registers on initialization. At the moment driver and devices are out of sync until the driver rewrites the configuration.

There is an issue in the periph.io library https://github.com/google/periph/issues/238 which prevents us from using the spi in half duplex (3-wire) mode, thus giving us no path to reading the ad9910 registers. However after this is resolved we should add this functionality.

At the same moment we should rethink the device-driver model used so far. I feel that the way the device is synced with the bytes resolved from the driver over spi is kind of artificial.

**Comment by bodokaiser** [comment]
https://github.com/geomatsi/nrf24-tools/blob/96adff620882db23644ae63b1a9b4bcc1e80c5f8/common/spi-spidev.c#L139-L159

**Comment by chrisgee** [comment]
I think there is no reason for a single byte half duplex transfer method. If you expect half duplex communication, you can just send padding bytes (zeros) to achieve that. This would also allow multibyte responses… which is not possible with the current implementation of half duplex communication.

> On 25 Apr 2018, at 14:13, Bodo Kaiser <notifications@github.com> wrote:
> 
> It would be preferable to read the dds state from the registers on initialization. At the moment driver and devices are out of sync until the driver rewrites the configuration.
> 
> There is an issue in the periph.io library google/periph#238 which prevents us from using the spi in half duplex (3-wire) mode, thus giving us no path to reading the ad9910 registers. However after this is resolved we should add this functionality.
> 
> At the same moment we should rethink the device-driver model used so far. I feel that the way the device is synced with the bytes resolved from the driver over spi is kind of artificial.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Christoph Gohle
christoph@gohle.org

**Comment by chrisgee** [comment]
a) 3-wire SPI is the only SPI variant that allows full duplex communication since the controller can then simultaneously send data on SDO and recieve on SDI while providing a clock on SCLK.

b) on the patch you have sent (where is it from?) there is a function spi_xfer_mfdx, that allows multibyte buffers txbuf and rxbuf. If you now have to send a two bytes to instruct the chip to read a register and the response is expected after these two bytes and e.g. four bytes long you would provide txbuf and rxbuf 6 bytes long txbuf containing [xx,xx,00,00,00,00]. rxbuf will then contain the response on the last four bytes. That’s what I mean with padding.

c) if your response is always 255, that either means your SPI slave is not configured correctly for 3-wire SPI or you have some other signal problem. I gues a scope is your friend.



> On 26 Apr 2018, at 10:20, Bodo Kaiser <notifications@github.com> wrote:
> 
> Isn't half duplex communication necessary because we use the SPI 3-wire? What do you mean with padding bytes? The spi interface only exposes a conn.Tx(w, r) with w bytes to write and r bytes to read. However r will just be 255, 255, 255, .....
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Christoph Gohle
christoph@gohle.org

**Comment by chrisgee** [comment]
Plus, some slaves (not sure for AD9910) sync on rising edge of CS. That is it would not be possible to first send a register request to the slave, have a rising edge on CS inbetween and then read back the result (the SPI state machine is reset, and not sending any data).

> On 26 Apr 2018, at 10:34, Christoph Gohle <christoph@gohle.org> wrote:
> 
> a) 3-wire SPI is the only SPI variant that allows full duplex communication since the controller can then simultaneously send data on SDO and recieve on SDI while providing a clock on SCLK.
> 
> b) on the patch you have sent (where is it from?) there is a function spi_xfer_mfdx, that allows multibyte buffers txbuf and rxbuf. If you now have to send a two bytes to instruct the chip to read a register and the response is expected after these two bytes and e.g. four bytes long you would provide txbuf and rxbuf 6 bytes long txbuf containing [xx,xx,00,00,00,00]. rxbuf will then contain the response on the last four bytes. That’s what I mean with padding.
> 
> c) if your response is always 255, that either means your SPI slave is not configured correctly for 3-wire SPI or you have some other signal problem. I gues a scope is your friend.
> 
> 
> 
>> On 26 Apr 2018, at 10:20, Bodo Kaiser <notifications@github.com> wrote:
>> 
>> Isn't half duplex communication necessary because we use the SPI 3-wire? What do you mean with padding bytes? The spi interface only exposes a conn.Tx(w, r) with w bytes to write and r bytes to read. However r will just be 255, 255, 255, .....
>> 
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> --
> Christoph Gohle
> christoph@gohle.org
> 
> 
> 
> 
> 
> 

--
Christoph Gohle
christoph@gohle.org

**Comment by bodokaiser** [comment]
This gives me `w: [129 0 0 0 0 130 0 0 0 0], r: [255 1 64 8 32 0 29 63 65 200]` as expected. Don't know what I did wrong yesterday...

```go
package main

import (
	"log"

	"periph.io/x/periph/conn/spi"
	"periph.io/x/periph/conn/spi/spireg"
	"periph.io/x/periph/host"
)

func main() {
	if _, err := host.Init(); err != nil {
		log.Fatal(err)
	}

	spiDev, err := spireg.Open("SPI1.0")
	if err != nil {
		log.Fatal(err)
	}

	spiConn, err := spiDev.Connect(50e3, spi.Mode0, 8)
	if err != nil {
		log.Fatal(err)
	}

	w := []byte{0x80 | 0x01, 0x00, 0x00, 0x00, 0x00, 0x80 | 0x02, 0x00, 0x00, 0x00, 0x00}
	r := make([]byte, len(w))

	err = spiConn.Tx(w, r)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("w: %v, r: %v\n", w, r)
}
```
